# Generated by Django 5.1.6 on 2025-05-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_food_place_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.TextField(default='Adres bulunamadı'),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
