# Generated by Django 5.1.6 on 2025-05-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_place_address_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='image_url',
            new_name='photo_url',
        ),
    ]
