# Generated by Django 5.1.6 on 2025-05-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_rename_image_url_place_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='photo_url',
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='destinations.place')),
            ],
        ),
    ]
