# Generated by Django 5.1.6 on 2025-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_remove_place_photo_url_placephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
