# Generated by Django 5.1.6 on 2025-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_place_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
