# Generated by Django 5.1.6 on 2025-05-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0011_alter_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_url',
            field=models.URLField(default=True),
        ),
        migrations.AddField(
            model_name='city',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
