# Generated by Django 5.1.6 on 2025-05-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_city_image_url_city_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
