# Generated by Django 5.1.6 on 2025-05-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0014_food_address_food_categories_food_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='yelp_id',
            new_name='place_id',
        ),
    ]
