# Generated by Django 5.1.6 on 2025-05-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0015_rename_yelp_id_food_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='price_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stay',
            name='types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stay',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
