# Generated by Django 5.1.6 on 2025-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0017_place_category_place_phone_place_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='tripadvisor_id',
            new_name='foursquare_id',
        ),
        migrations.AddField(
            model_name='place',
            name='hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='place',
            name='price_tier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
