# Generated by Django 5.1.6 on 2025-05-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0018_rename_tripadvisor_id_place_foursquare_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='foursquare_id',
        ),
        migrations.AddField(
            model_name='place',
            name='opentripmap_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='hours',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='price_tier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
