# Generated by Django 5.1.6 on 2025-05-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0020_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='price_tier',
        ),
        migrations.RemoveField(
            model_name='place',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='place',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='place',
            name='website',
        ),
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
