# Generated by Django 5.1.6 on 2025-05-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0021_alter_place_options_remove_place_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_url',
        ),
    ]
